export const productList = [
  {
    id: 1,
    brand: 'Jumper',
    model: 'X7',
    price: '549.99',
    imgUrl: 'https://m.media-amazon.com/images/I/81nN15A4msL._AC_SX679_.jpg',
    specs: {
      CPU: 'Core i5-1035G1',
      GPU: 'Integrated',
      RAM: '24 GB',
      display: '14 Inches',
      hardDisk: '1024GB SSD',
    },
  },
  {
    id: 2,
    brand: 'HP',
    model: 'HP',
    price: '529.00',
    imgUrl: 'https://m.media-amazon.com/images/I/61DF0nkzgxL._AC_SX355_.jpg',
    specs: {
      CPU: 'Core i3',
      GPU: 'Intel UHD Graphics',
      RAM: '16 GB',
      display: '17.3 Inches',
      hardDisk: '256GB SSD',
    },
  },
  {
    id: 3,
    brand: 'Lenovo',
    model: 'Ideapad 3i',
    price: '518.25',
    imgUrl: 'https://m.media-amazon.com/images/I/61ZQGFMxi9L._AC_SX355_.jpg',
    specs: {
      CPU: 'Core i3',
      GPU: 'Integrated',
      RAM: '8 GB',
      display: '15.6 Inches',
      hardDisk: '512GB HDD',
    },
  },
  {
    id: 4,
    brand: 'HP',
    model: 'Pavilion',
    price: '765.00',
    imgUrl: 'https://m.media-amazon.com/images/I/71H6BVX8MkL._AC_SX466_.jpg',
    specs: {
      CPU: 'Core i7-1255U',
      GPU: 'Integrated',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '512GB SSD',
    },
  },
  {
    id: 5,
    brand: 'ASUS',
    model: 'Vivobook Pro 15',
    price: '1,399.99',
    imgUrl: 'https://m.media-amazon.com/images/I/61ZQGFMxi9L._AC_SX355_.jpg',
    specs: {
      CPU: 'AMD Ryzen 9 7940HS',
      GPU: 'NVIDIA GeForce RTX 4060',
      RAM: '32 GB',
      display: '15.6 Inches',
      hardDisk: '1TB SSD',
    },
  },
  {
    id: 6,
    brand: 'Lenovo',
    model: 'IdeaPad Gaming 3',
    price: '691.96',
    imgUrl: 'https://m.media-amazon.com/images/I/81zcUyiNcUL._AC_SY355_.jpg',
    specs: {
      CPU: 'AMD Ryzen 5 6600H',
      GPU: 'NVIDIA GeForce RTX 3050',
      RAM: '32 GB',
      display: '15.6 Inches',
      hardDisk: '256GB SSD',
    },
  },
  {
    id: 7,
    brand: 'Acer',
    model: 'Aspire 5',
    price: '619.00',
    imgUrl: 'https://m.media-amazon.com/images/I/61HGNTwSQBL._AC_SX355_.jpg',
    specs: {
      CPU: 'AMD Ryzen 5 5500U',
      GPU: 'AMD Radeon Graphics',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '512GB SSD',
    },
  },
  {
    id: 8,
    brand: 'ASUS',
    model: 'VivoBook',
    price: '569.00',
    imgUrl: 'https://m.media-amazon.com/images/I/71LUaWkkszL._AC_SX450_.jpg',
    specs: {
      CPU: 'Intel Core i3-1115G4',
      GPU: 'Intel HD Graphics 5000',
      RAM: '20 GB',
      display: '15.6 Inches',
      hardDisk: '1TB SSD',
    },
  },
  {
    id: 9,
    brand: 'Acer',
    model: 'Nitro 5',
    price: '849.99',
    imgUrl: 'https://m.media-amazon.com/images/I/71ctRE34RuL._AC_SX355_.jpg',
    specs: {
      CPU: 'Intel Core i5-12500H',
      GPU: 'NVIDIA GeForce RTX 3050 Ti',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '512GB SSD',
    },
  },
  {
    id: 10,
    brand: 'Dell',
    model: 'Inspiron 15 3000',
    price: '560.00',
    imgUrl: 'https://m.media-amazon.com/images/I/61KwCmF0bdL._AC_SY355_.jpg',
    specs: {
      CPU: 'Intel Core i5-1035G1',
      GPU: 'Integrated',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '512GB SSD',
    },
  },
  {
    id: 11,
    brand: 'Dell',
    model: 'Inspiron 15 3520',
    price: '899.99',
    imgUrl: 'https://m.media-amazon.com/images/I/61bDAazJikL._AC_SX355_.jpg',
    specs: {
      CPU: 'Intel Core i7-1255U',
      GPU: 'Intel Iris Xe Graphics',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '1TB SSD',
    },
  },
  {
    id: 12,
    brand: 'HP',
    model: 'Pavilion',
    price: '569.00',
    imgUrl: 'https://m.media-amazon.com/images/I/61qw1PevupL._AC_SX355_.jpg',
    specs: {
      CPU: 'Intel Pentium N5000',
      GPU: 'Integrated',
      RAM: '32 GB',
      display: '15.6 Inches',
      hardDisk: '1TB SSD',
    },
  },
  {
    id: 13,
    brand: 'Asus',
    model: 'Vivobook S 14',
    price: '749.99',
    imgUrl: 'https://m.media-amazon.com/images/I/615KMBqkbSL._AC_SX355_.jpg',
    specs: {
      CPU: 'Ryzen 5 5600H',
      GPU: 'AMD Radeon graphics',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '1TB SSD',
    },
  },
  {
    id: 14,
    brand: 'Asus',
    model: 'Zenbook 14',
    price: '735.00',
    imgUrl: 'https://m.media-amazon.com/images/I/71ZzdjSmtqL._AC_SY450_.jpg',
    specs: {
      CPU: 'Intel Evo i5-1240P',
      GPU: 'Intel Iris Xe Graphics',
      RAM: '8 GB',
      display: '15.6 Inches',
      hardDisk: '512GB SSD',
    },
  },
  {
    id: 15,
    brand: 'HP',
    model: 'Envy x360',
    price: '799.99',
    imgUrl: 'https://m.media-amazon.com/images/I/61xZQJhpuXL._AC_SX355_.jpg',
    specs: {
      CPU: 'AMD Ryzen 7 5825U',
      GPU: 'AMD Radeon Graphics',
      RAM: '16 GB',
      display: '15.6 Inches',
      hardDisk: '1TB SSD',
    },
  },
  {
    id: 16,
    brand: 'HP',
    model: 'Envy Business',
    price: '1,190.00',
    imgUrl: 'https://m.media-amazon.com/images/I/71KEl2itHNL._AC_SY355_.jpg',
    specs: {
      CPU: 'Intel Core i7-1260P',
      GPU: 'Integrated',
      RAM: '64 GB',
      display: '17.3 Inches',
      hardDisk: '2TB SSD',
    },
  },
  {
    id: 17,
    brand: 'Acer',
    model: 'Nitro 17',
    price: '1,449.99',
    imgUrl: 'https://m.media-amazon.com/images/I/711+0tgn+6L._AC_SY450_.jpg',
    specs: {
      CPU: 'AMD Ryzen 7 7735HS',
      GPU: 'NVIDIA GeForce RTX 4070',
      RAM: '16 GB',
      display: '17.3 Inches',
      hardDisk: '1TB SSD',
    },
  },
]
